### ISSUE TITLE
Barrel recipe overrides all Minecraft barrel recipes wood types.

### ISSUE THREAD

**Issue by Neonis00** [spoorn/SpoornPink#4]
Version: "spoornpink-3.3"
--> "spoornpacks-4.2-1.18.2"

The barrel recipe is overriding all barrel recipes, causing every wood type to craft Pink Blossom Barrel.

Example images:
![image](https://user-images.githubusercontent.com/47197231/162600765-b1e24e6e-5a93-43b3-b960-231e16f09ea9.png)
![image](https://user-images.githubusercontent.com/47197231/162600775-1601ebc8-ec6f-44df-8692-1f399f58dcc0.png)
![image](https://user-images.githubusercontent.com/47197231/162600782-7d5c596b-ff31-489a-ba95-b933a831925e.png)

**Comment by spoorn** [comment]
This is expected behavior.  The Barrel recipe is supposed to use the #minecraft:planks tag and #minecraft:slabs.  This is even the behavior of vanilla barrel recipes:

**Vanilla**:

```json
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "PSP",
    "P P",
    "PSP"
  ],
  "key": {
    "P": {
      "tag": "minecraft:planks"
    },
    "S": {
      "tag": "minecraft:wooden_slabs"
    }
  },
  "result": {
    "item": "minecraft:barrel"
  }
}
```


**SpoornPink:**
```json
{
  "type" : "minecraft:crafting_shaped",
  "pattern" : [
    "PSP",
    "P P",
    "PSP"
  ],
  "key" : {
    "P" : {
      "tag" : "minecraft:planks"
    },
    "S" : {
      "tag" : "minecraft:wooden_slabs"
    }
  },
  "result" : {
    "item" : "spoornpink:pink_blossom_barrel"
  }
}
```

You'll probably find this happening with other mods' recipes as any recipe that uses tags can "conflict".  I'd recommend using the Polymorph mod which adds a button letting you choose exactly which recipe you want to craft: https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric

![image](https://user-images.githubusercontent.com/12925899/162604985-f6262acf-1273-4c9d-8e6c-e0fdec86b6e8.png)



## **_If I instead changed the Pink Blossom Barrel to use Pink Blossom Planks/Slabs only, the vanilla recipe may override my recipe._**

**Comment by xanthian** [comment]
I think you find this wouldn't be the case and should be changed so that it does indeed use your pink planks/slabs.
